export const UPDATE_ACTIVE_TAB = "UPDATE_ACTIVE_TAB";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const VALIDATE_CONTACT_SHAREHOLDER = "VALIDATE_CONTACT_SHAREHOLDER";
export const CLICK_BUTTON_UPDATE_EDIT = "CLICK_BUTTON_UPDATE_EDIT";
export const CHANGE_VALUE_MODAL_ERRORS = "CHANGE_VALUE_MODAL_ERRORS";
export const MESSAGE_ERRORS_UPDATE = "MESSAFE_ERRORS_UPDATE";
export const BUTTON_UPDATE = "BUTTON_UPDATE";
export const BUTTON_EDIT = "BUTTON_EDIT";
