export const GET_LINK_REQUESTS = 'GET_LINK_REQUESTS';
export const NUMBER_RECORDS = 10;
export const PAGE_INITIAL = 0;
export const LIMITE_INF = 'LIMITE_INF_LINK_REQUESTS';
export const CHANGE_PAGE = 'CHANGE_PAGE_LINK_REQUESTS';
export const GET_OBSERVATIONS_BY_LINKING_REQUESTS = 'GET_OBSERVATIONS_BY_LINKING_REQUESTS';
export const CLEAR_LIST_OBSERVATIONS = 'CLEAR_LIST_OBSERVATIONS';
export const SAVE_OBSERVATION = 'SAVE_OBSERVATION';