export const VALIDATE_PROSPECT_EXISTS = "VALIDATE_PROSPECT_EXISTS";
export const CLEAR_STATE_PROSPECT = "CLEAR_STATE_PROSPECT";
export const CLEAR_ALL_PROSPECT = "CLEAR_ALL_PROSPECT";
export const CREATE_PROSPECT = "CREATE_PROSPECT";
export const NATURE_PERSON = "Persona natural";