/**
 * Created by ahurtado on 12/06/2016
 */
export const FIND_CLIENTS_PORTFOLIO_EXPIRATION = "FIND_CLIENTS_PORTFOLIO_EXPIRATION";
export const NUMBER_RECORDS = 10;
export const CHANGE_PAGE_FOR_ALERT_PORTFOLIO_EXPIRATION = "CHANGE_PAGE_FOR_ALERT_PORTFOLIO_EXPIRATION";
export const CHANGE_KEYWORD_NAME_NIT_PE = "CHANGE_KEYWORD_NAME_NIT_PE";
export const CLEAR_FILTER_CLIENTS_PE = "CLEAR_FILTER_CLIENTS_PE";
export const CLEAR_CLIENT_ORDER_PE = "CLEAR_CLIENT_ORDER__PE";
export const CLEAR_CLIENT_PAGINATION_PE = "CLEAR_CLIENT_PAGINATION_PE";
export const ORDER_COLUMN_CLIENT_PE = "ORDER_COLUMN_CLIENT_PE";
export const UPDATE_NUMBER_TOTAL_CLIENTS_PE = "UPDATE_NUMBER_TOTAL_CLIENTS_PE";
export const CHANGE_TEAM_PE = "CHANGE_TEAM_PE";
export const CHANGE_REGION_PE = "CHANGE_REGION_PE";
export const CHANGE_ZONE_PE = "CHANGE_ZONE_PE";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_LINE = "CHANGE_LINE";
export const FORM_FILTER_ALERT_PE = "formFilterAlertPE";
export const SAVE_OBSERVATIONS = "SAVE_OBSERVATIONS";


