export const PROPUEST_OF_BUSINESS = "Propuesta";
export const CREATE_PREVISIT = "CREATE_PREVISIT";
export const NUMBER_RECORDS = 10;
export const GET_PREVISIT_LIST = 'GET_PREVISIT_LIST';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const LIMITE_INF = 'LIMITE_INF';
export const CLEAR_PREVISIT_PAGINATOR = 'CLEAR_PREVISIT_PAGINATOR';
export const CLEAR_PREVISIT_ORDER = 'CLEAR_PREVISIT_ORDER';
export const ORDER_COLUMN_PREVISIT = 'ORDER_COLUMN_PREVISIT';
export const CLEAR_PREVISIT = 'CLEAR_PREVISIT';
export const DELETE_TYPE_PREVISIT= 'DELETE_TYPE_PREVISIT';
export const FILTER_STATUS_PREVISIT_ID = 'FILTER_STATUS_PREVISIT_ID';
export const GET_DETAIL_PREVISIT = "GET_DETAIL_PREVISIT";
export const OWNER_DRAFT = "OWNER_DRAFT";
export const GET_CSV_PREVISIT_BY_CLIENT = 'GET_CSV_PREVISIT_BY_CLIENT';
export const ASK_EDIT_PREVISITA = 'ASK_EDIT_PREVISITA';
export const DELETE_BLOCKED_PREVISITA = 'DELETE_BLOCKED_PREVISITA'

