export const TAB_STORY = 1;
export const TAB_CUSTOMER_DELIVERY = 2;
export const UPDATE_ACTIVE_TAB_CS = "UPDATE_ACTIVE_TAB_CS";
export const VALIDATE_CLIENTS = "VALIDATE_CLIENTS";
export const UPDATE_TEAM_CLIENTS = "UPDATE_TEAM_CLIENTS";
export const APROVE_DELIVERY_CLIENT = "APROVE_DELIVERY_CLIENT";
export const GET_ALL_TEAMS = "GET_ALL_TEAMS";