export const CONSULT_RISK_GROUP = "CONSULT_RISK_GROUP";
export const REMOVE_CLIENT_RISK_GROUP = "REMOVE_CLIENT_RISK_GROUP";
export const DELETE_RISK_GROUP = "DELETE_RISK_GROUP";
export const ADD_CLIENT_RISK_GROUP = "ADD_CLIENT_RISK_GROUP";
export const EDIT_NAME_RISK_GROUP = "EDIT_NAME_RISK_GROUP";


