export const CONSULT_RISK_GROUP = "CONSULT_RISK_GROUP";
export const REMOVE_CLIENT_RISK_GROUP = "REMOVE_CLIENT_RISK_GROUP";
export const DELETE_RISK_GROUP = "DELETE_RISK_GROUP";
export const ADD_CLIENT_RISK_GROUP = "ADD_CLIENT_RISK_GROUP";
export const EDIT_NAME_RISK_GROUP = "EDIT_NAME_RISK_GROUP";
export const UPDATE_NAME_RISK_GROUP = "UPDATE_NAME_RISK_GROUP";
export const HAS_RISK_GROUP = "HAS_RISK_GROUP";
export const CHANGE_PENDING = "CHANGE_PENDING";
export const VALIDATE_RISK_GROUP_CODE_EXITS = "VALIDATE_RISK_GROUP_CODE_EXITS";


