export const FILTER_CONTACTS = "FILTER_CONTACTS";
export const NUMBER_RECORDS = 20;
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_KEYWORD = "CHANGE_KEYWORD";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";
export const CHANGE_VALUE_IS_OPEN = "CHANGE_VALUE_IS_OPEN";
export const SET_EDIT_RELATIONSHIP = "SET_EDIT_RELATIONSHIP";
export const UPDATE_VALUES_RELATIONSHIP = "UPDATE_VALUES_RELATIONSHIP";