export const MY_PENDINGS_TITLE = "Mis tareas";
export const MY_PENDINGS_BY_TEAM_TITLE = "Mis tareas por célula";

export const FIND_PENDING_TASKS = 'FIND_PENDING_TASKS';

export const NUMBER_RECORDS = 10;
export const LIMITE_INF = 'LIMITE_INF';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CLEAR_PENDING_TASK = 'CLEAR_PENDING_TASK';
export const CLEAR_MY_PENDINGS_ORDER = 'CLEAR_MY_PENDINGS_ORDER';
export const CLEAR_MY_PENDINGS_PAGINATOR = 'CLEAR_MY_PENDINGS_PAGINATOR';
export const ORDER_COLUMN_MY_PENDING = 'ORDER_COLUMN_MY_PENDING';
export const GET_INFO_USERTASK = 'GET_INFO_USERTASK';
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK';
export const CLEAR_LIST_MY_PENDINGS = 'CLEAR_LIST_MY_PENDINGS';
export const GET_DOWNLOAD_PENDINGS_TASKS  = 'GET_DOWNLOAD_PENDINGS_TASKS';
export const UPDATE_USERNAME_TASK = "UPDATE_USERNAME_TASK";

export const FIND_PENDING_TASKS_TEAM = 'FIND_PENDING_TASKS_TEAM';
export const CHANGE_PAGE_TEAM = 'CHANGE_PAGE_TEAM';
export const LIMITE_INF_TEAM = 'LIMITE_INF_TEAM';
export const CLEAR_MY_PENDINGS_PAGINATOR_TEAM = 'CLEAR_MY_PENDINGS_PAGINATOR_TEAM';
export const CLEAR_LIST_MY_PENDINGS_TEAM = 'CLEAR_LIST_MY_PENDINGS_TEAM';
export const ORDER_COLUMN_MY_PENDING_TEAM = 'ORDER_COLUMN_MY_PENDING_TEAM';
export const CLEAR_PENDING_TASK_TEAM = 'CLEAR_PENDING_TASK_TEAM';