export const DELETE_TYPE_CONTACT = "DELETE_TYPE_CONTACT";
export const DELETE_TYPE_SHAREHOLDER = "DELETE_TYPE_SHAREHOLDER";
export const DELETE_TYPE_VISIT = "DELETE_TYPE_VISIT";
export const NUMBER_RECORDS = 10;
