export const DELETE_TYPE_CONTACT = "DELETE_TYPE_CONTACT";
export const DELETE_TYPE_SHAREHOLDER = "DELETE_TYPE_SHAREHOLDER";
export const NUMBER_RECORDS = 10;
export const DELETE_PARTICIPANT_VIEW = "DELETE_PARTICIPANT_VIEW";
