
export const FIND_GROUP_FAVORITE_CONTACTS = "FIND_GROUP_FAVORITE_CONTACTS";
export const NUMBER_RECORDS = 10;
export const CHANGE_PAGE_FOR_GROUP = "CHANGE_PAGE_FOR_GROUP";
export const CHANGE_KEYWORD_NAME_GROUP = "CHANGE_KEYWORD_NAME_GROUP";
export const INITIAL_VALUES_GROUPS = "INITIAL_VALUES_GROUPS";
export const DELETE_GROUP  = "DELETE_GROUP";
export const VIEW_LINK_GROUP = "VIEW_LINK_GROUP";
export const VIEW_EMAIL_CONTACTS = "VIEW_EMAIL_CONTACTS";
export const TITTLE_MODAL_GROUP = "grupo de contactos favoritos";
export const GET_GROUP_FOR_ID = "GET_GROUP_FOR_ID";
export const CHANGE_KEYWORD_NAME_NEW_GROUP = "CHANGE_KEYWORD_NAME_NEW_GROUP";
export const GET_LIST_CONTACT_GROUP_FOR_ID= "GET_LIST_CONTACT_GROUP_FOR_ID";
export const DELETE_CONTACT_LIST_GROUP= "DELETE_CONTACT_LIST_GROUP";
export const VALID_EXISTS_GROUP= "VALID_EXISTS_GROUP";
export const SEARCH_CONTACT_FOR_GROUP= "SEARCH_CONTACT_FOR_GROUP";
export const ADD_CONTACT_LIST= "ADD_CONTACT_LIST";
export const CLEAR_CONTACT_NAME= "CLEAR_CONTACT_NAME";
export const DELETE_CONTACT_LIST = "DELETE_CONTACT_LIST";
export const SAVE_GROUP_FAVORITE_CONTACTS = "SAVE_GROUP_FAVORITE_CONTACTS";
export const RESET_MODAL = "RESET_MODAL";
export const MODAL_TITLE_EMAILS = "Correos electronicos del grupo";
export const SAVE_NAME_GROUP = "SAVE_NAME_GROUP";

