export const CREATE_LIST = "CREATE_LIST";
export const ADD_FIELD_TO_LIST = "ADD_FIELD_TO_LIST";
export const SET_FIELDS_TO_LIST = "SET_FIELDS_TO_LIST";
export const CHANGE_LIST_STATE = "FIELD-LIST_CHANGE_LIST_STATE";
export const UPDATE_ELEMENT_FROM_LIST = "FIELD-LIST_ADD_ELEMENT_FROM_LIST";
export const REMOVE_ELEMENT_FROM_LIST = "FIELD-LIST_REMOVE_ELEMENT_FROM_LIST";
export const EDIT_ELEMENT_FROM_LIST = "FIELD-LIST_EDIT_ELEMENT_FROM_LIST"
export const CHANGE_DRAFT_LIST_STATE = "FIELD-LIST_CHANGE_DRAFT_LIST_STATE";