export const KEY_DESMONTE = "Desmonte";
export const KEY_EXCEPCION_NO_GERENCIADO = "Excepción no gerenciado";
export const TITLE_DESCRIPTION = "Diligencie esta sección respondiendo a la pregunta ¿Qué debería conocer el Grupo Bancolombia de este cliente? (quién es, qué hace, cuáles son sus principales líneas de negocio, productos y servicios que ofrece, sector donde se encuentra, estrategia, países en los que tiene presencia, participación de mercado).";
export const MAXIMUM_OPERATIONS_FOREIGNS = 3;
export const KEY_OPTION_OTHER_OPERATIONS_FOREIGNS = "Otro";
export const KEY_OPTION_OTHER_ORIGIN_GOODS = "Otro";
export const KEY_OPTION_OTHER_ORIGIN_RESOURCE = "Otro";
export const GOVERNMENT = "Gobierno";
export const CONSTRUCT_PYME = "Constructor Pyme";
