export const CLIENTS_FIND = "CLIENTS_FIND";
export const NUMBER_RECORDS = 20;
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_KEYWORD = "CHANGE_KEYWORD";
export const CLEAR_CLIENTS = "CLEAR_CLIENTS";
export const CLIENTS_FIND_TYPE_NUMBER_BASIC = "CLIENTS_FIND_TYPE_NUMBER_BASIC";
export const MAX_LENGTH_NAME_CLIENT = 50;
export const MAX_LENGTH_DOCUMENT = 20;
export const MAX_LENGTH_ECONOMIC_GROUP = 30;
export const ID_OPTION_ALL_LEVEL_AEC = -1;
export const AEC_NO_APLICA = "AEC: No aplica";
export const GET_RECENT_CLIENTS = 1;
export const DELETE_ALL_RECENT_CLIENTS = 2;
export const DELETE_RECENT_CLIENT = 3;
export const SAVE_FILTER = "SAVE_FILTER";
export const BACK_BUTTON_FILTER = "BACK_BUTTON_FILTER";
export const CLEAR_SAVE_FILTER = "CLEAR_SAVE_FILTER";
export const MESSAGE_PLACEHOLDER = "Búsqueda por número de documento, nombre, cargo."