export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const CLEAR_PARTICIPANTS = "CLEAR_PARTICIPANTS";
export const ADD_LIST_PARTICIPANT = "ADD_LIST_PARTICIPANT";
export const KEY_PARTICIPANT_CLIENT = "client";
export const NUMBER_CONTACTS = 300;

