export const FIND_ALERT_COVENANTS = "FIND_ALERT_COVENANTS";
export const NUMBER_RECORDS = 10;
export const CHANGE_PAGE_FOR_COVENANTS = "CHANGE_PAGE_FOR_COVENANTS";
export const CHANGE_KEYWORD_NAME_NIT_COVENANT = "CHANGE_KEYWORD_NAME_NIT_COVENANT";
export const CLEAR_FILTER_ALERT_COVENANT = "CLEAR_FILTER_ALERT_COVENANT";
export const CLEAR_CLIENT_ORDER = "CLEAR_CLIENT_ORDER";
export const CLEAR_CLIENT_PAGINATION = "CLEAR_CLIENT_PAGINATION";
export const ORDER_COLUMN_CLIENT = "ORDER_COLUMN_CLIENT";
export const UPDATE_NUMBER_TOTAL_COVENANTS = "UPDATE_NUMBER_TOTAL_COVENANTS";
export const CHANGE_STATUS_COVENANT = "CHANGE_STATUS_COVENANT";
export const INITIAL_VALUES = "INITIAL_VALUES";
export const FORM_FILTER_ALERT_COVENANT = "formFilterAlertCovenant";

