export const SAVE_DATA_LOADING = 'SAVE_DATA_LOADING';
export const PRODUCTION_UPGRADE_REQUEST = 'PRODUCTION_UPGRADE_REQUEST';
export const PRODUCTION_UPGRADE_NOTIFIED = 'PRODUCTION_UPGRADE_NOTIFIED';
export const VALID_TOKEN = "VALID_TOKEN";