/**
 * Created by dloaiza on 26/04/2017
 */
export const FIND_CONTACTS_BY_FUNCTION_OR_TYPE = "FIND_CONTACTS_BY_FUNCTION_OR_TYPE";
export const NUMBER_RECORDS = 10;
export const CHANGE_PAGE_FOR_CONTACTS_BY_FUNCTION_OR_TYPE= "CHANGE_PAGE_FOR_CONTACTS_BY_FUNCTION_OR_TYPE";
export const CLEAR_FILTERS_CONTACTS_BY_FUNCTION_OR_TYPE = "CLEAR_FILTERS_CONTACTS_BY_FUNCTION_OR_TYPE";
export const CLEAR_ORDER_CONTACTS_BY_FUNCTION_OR_TYPE = "CLEAR_ORDER_CONTACTS_BY_FUNCTION_OR_TYPE";
export const CLEAR_PAGINATION_CONTACTS_BY_FUNCTION_OR_TYPE = "CLEAR_PAGINATION_CONTACTS_BY_FUNCTION_OR_TYPE";
export const ORDER_COLUMN_CONTACTS_BY_FUNCTION_OR_TYPE = "ORDER_COLUMN_CONTACTS_BY_FUNCTION_OR_TYPE";
export const CHANGE_FUNCTION_CONTACTS_BY_FUNCTION_OR_TYPE = "CHANGE_FUNCTION_CONTACTS_BY_FUNCTION_OR_TYPE";
export const CHANGE_TYPE_CONTACTS_BY_FUNCTION_OR_TYPE = "CHANGE_TYPE_CONTACTS_BY_FUNCTION_OR_TYPE";
export const CHANGE_TYPE_CONTACTS_BY_POSITION_OR_TYPE = "CHANGE_TYPE_CONTACTS_BY_POSITION_OR_TYPE";
export const CHANGE_TYPE_CONTACTS_BY_DEPENDENCY_OR_TYPE = "CHANGE_TYPE_CONTACTS_BY_DEPENDENCY_OR_TYPE";
export const FORM_FILTERS_CONTACT_BY_FUNCTION_OR_TYPE = "formFiltersContactByFunction";
export const DELETE_MESSAGE = "Señor usuario ¿está seguro que desea eliminar el contacto ";
export const DELETE_CONTACT_FROM_FUNCTION_OR_TYPE = "DELETE_CONTACT_FROM_FUNCTION_OR_TYPE";