/**
 * Created by ahurtado on 11/23/2016.
 */
export const CLIENTS_FIND_FOR_ALERT_PENDING_UPDATE = "CLIENTS_FIND_FOR_ALERT_PENDING_UPDATE";
export const NUMBER_RECORDS = 10;
export const CHANGE_PAGE_FOR_ALERT_PENDING_UPDATE = "CHANGE_PAGE_FOR_ALERT_PENDING_UPDATE";
export const CHANGE_KEYWORD_NAME_NIT = "CHANGE_KEYWORD_NAME_NIT";
export const CLEAR_FILTER = "CLEAR_FILTER";