export const CLIENTS_FIND_FOR_ALERT_PENDING_UPDATE = "CLIENTS_FIND_FOR_ALERT_PENDING_UPDATE";
export const NUMBER_RECORDS = 10;
export const CHANGE_PAGE_FOR_ALERT_PENDING_UPDATE = "CHANGE_PAGE_FOR_ALERT_PENDING_UPDATE";
export const CHANGE_KEYWORD_NAME_NIT = "CHANGE_KEYWORD_NAME_NIT";
export const CLEAR_FILTER_CLIENTS_PENDING_UPDATE = "CLEAR_FILTER_CLIENTS_PENDING_UPDATE";
export const CLEAR_CLIENT_ORDER = "CLEAR_CLIENT_ORDER";
export const CLEAR_CLIENT_PAGINATION = "CLEAR_CLIENT_PAGINATION";
export const ORDER_COLUMN_CLIENT = "ORDER_COLUMN_CLIENT";
export const UPDATE_NUMBER_TOTAL_CLIENTS = "UPDATE_NUMBER_TOTAL_CLIENTS";
export const CHANGE_TEAM = "CHANGE_TEAM";
export const CHANGE_REGION = "CHANGE_REGION";
export const CHANGE_ZONE = "CHANGE_ZONE";
export const FORM_FILTER_ALERT_PUC = "formFilterAlertPUC";

