export const TOGGLE_MODAL_SHAREHOLDER = "TOGGLE_MODAL_SHAREHOLDER";
export const CLEAR_SEARCH_SHAREHOLDER = "CLEAR_SEARCH_SHAREHOLDER";
export const SEARCH_SHAREHOLDER = "SEARCH_SHAREHOLDER";

export const TYPE_OF_DOCUMENT_FOREIGN_PJ= 469;
export const TYPE_OF_DOCUMENT_NIT= 468;

export const TYPE_OF_DOCUMENT_FOREIGN_PN= 467;
export const TYPE_OF_DOCUMENT_DIPLOMATIC_CARD = 464;
export const TYPE_OF_DOCUMENT_CITIZENCHIP_CARD = 461;
export const TYPE_OF_DOCUMENT_FOREIGN_CITIZENCHIP_CARD = 462;
export const TYPE_OF_DOCUMENT_PASSPORT = 463;
export const TYPE_OF_DOCUMENT_CIVIL_REGISTRATION = 465;
export const TYPE_OF_DOCUMENT_IDENTITY_CARD = 466;

export const TYPE_OF_PERSON_PN = 451;
export const TYPE_OF_PERSON_PJ = 452;
