/**
 * Created by IAS-ASUS on 2/3/2017.
 */
export const  CLIENTS_COVENANTS = 'CLIENTS_COVENANTS';
export const  CONSULT_INFO_COVENANT = 'CONSULT_INFO_COVENANT';
export const  CLEAR_COVENANT = 'CLEAR_COVENANT';