export const ADD_LIST_USER = "ADD_LIST_PARTICIPANT";
export const CLEAR_USER = "CLEAR_PARTICIPANTS";
export const FILTER_USER = "FILTER_USER";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";

export const DELETE_PARTICIPANT_VIEW = "DELETE_PARTICIPANT_VIEW";
export const KEY_PARTICIPANT_BANCO = "banco";