export const OPPORTUNITIES = "opportunities";
export const WEAKNESSES = "weaknesses";
export const OPPORTUNITIES_PLACEHOLDER = `Factores externos que representan posibles ingresos para el cliente. Pueden ser: cambios en el sector económico. Normativas, movimiento de la competencia, tendencia de sus consumidores, mercados geográficos. economía, tendencias del mercado, benchmarks. `;
export const WEAKNESSES_PLACEHOLDER =  `Aspectos internos negativos del cliente que no le permiten  el crecimiento empresarial o que frenan el cumplimiento de sus objetivos y que debe controlarlos para superarlos. Pueden ser: Localizaciones, marca y reputación, idealización de los clientes, capital humano, tecnologías, canales, liderazgo, calidad del producto, situación financiera, etc.`;
export const TITLE_OPPORTUNITIES = "Oportunidades (externas)";
export const TITLE_WEAKNESSES = "Debilidades (internas del cliente)"
export const SINGULAR_TITLE_OPPORTUNITIES = "Oportunidades";
export const SINGULAR_TITLE_WEAKNESSES = "Debilidades"
export const MSG_HELP_OPPORTUNITIES = `Factores externos que representan posibles ingresos para el cliente. Pueden ser: cambios en el sector económico. Normativas, movimiento de la competencia, tendencia de sus consumidores, mercados geográficos. economía, tendencias del mercado, benchmarks. `;
export const MSG_HELP_WEAKNESSES = `Aspectos internos negativos del cliente que no le permiten  el crecimiento empresarial o que frenan el cumplimiento de sus objetivos y que debe controlarlos para superarlos. Pueden ser: Localizaciones, marca y reputación, idealización de los clientes, capital humano, tecnologías, canales, liderazgo, calidad del producto, situación financiera, etc.`;
