export const TOGGLE_MODAL_CONTACT = "TOGGLE_MODAL_CONTACT";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const SEARCH_CONTACT = "SEARCH_CONTACT";
export const CLEAR_SEARCH_CONTACT = "CLEAR_SEARCH_CONTACT";
