export const TOGGLE_MENU = "TOGGLE_MENU";
export const UPDATE_TITLE_NAV_BAR = "UPDATE_TITLE_NAV_BAR";
export const CONSULT_MODULE_ACCESS = "CONSULT_MODULE_ACCESS";
export const VIEW_ALERT_CLIENT = "ALERT_CLIENT";
export const SHOW_BRAND_CONFIDENTIAL = "SHOW_BRAND_CONFIDENTIAL";
