export const NUMBER_RECORDS = 10;
export const GET_SHAREHOLDERS_LIST_CLIENT = 'GET_SHAREHOLDERS_LIST_CLIENT';
export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';
export const CLEAR_SHAREHOLDERS = "CLEAR_SHAREHOLDERS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const LIMITE_INF = "LIMITE_INF";
