export const GET_AEC_FOR_EMPLOYEE = 'GET_AEC_FOR_EMPLOYEE';
export const SAVE_COMMERCIAL_OBSERVATIONS = 'SAVE_COMMERCIAL_OBSERVATIONS';
export const GET_DETAIL_AEC = 'GET_DETAIL_AEC';
export const CLEAR_DETAIL_AEC = 'CLEAR_DETAIL_AEC';
export const NUMBER_RECORDS = 10;
export const LIMITE_INF = 'LIMITE_INF';
export const CHANGE_PAGE = 'CHANGE_PAGE';