export const UPDATE_LIST = "LISTA-UPDATE_LIST";
export const UPDATE_ACTIVE_FIELD_OBJECT = "LISTA-UPDATE_ACTIVE_FIELD_OBJECT";

export const UPDATE_ELEMENT_ASOCIADO = "LISTA-UPDATE-ELEMENT-ASOCIADO";
export const SAVE_TEMPORAL_CHANGES = "SAVE_TEMPORAL_CHANGES";
export const DISCARD_TEMPORAL_CHANGES = "DISCARD_TEMPORAL_CHANGES";
