export const SET_URL_PARAMETER = "SET_URL_PARAMETER";
export const MODULE_WALLET_SHARE_TITLE = "Wallet share de cartera";
export const FUND_FLOWS_TITLE = "Flujo de fondos";
export const VISOR_CONSOLIDATE_TITLE = "Consolidado IG VEG";

export const CONTROL_DASHBOARD_TITLE = "Tablero de control";
export const PARAMETER_WALLET_SHARE_URL = "WALLET_SHARE_URL";
export const PARAMETER_FUND_FLOWS_URL = "FLUJO_DE_FONDOS_URL";
export const PARAMETER_TRANSACTIONAL_URL= "CONTENEDOR_VISOR_URL";
export const CONTROL_DASHBOARD_URL_PARAMETER = "TABLERO_DE_CONTROL_URL";
export const VISOR_CONSOLIDATE_REPORT_URL = "VISOR_CONSOLIDATE_REPORT_URL";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";