export const OPTION_MANAGER = "Gerentes";
export const OPTION_OTHERS = "Otros";
export const OPTION_ASSISTANTS = "Asistentes";
export const TEAM_PARTICIPANTS = "TEAM_PARTICIPANTS";
export const MANAGER = "MANAGER";
export const OTHER = "OTHER";
export const ASSISTANT = "ASSISTANT";
export const SAVE_SENIOR_BANKER = "SAVE_SENIOR_BANKER";
export const SENIOR_BANKER_BACK_UP = "Banquero Senior (Backup)";
