export const DELETE_PARTICIPANT_VIEW = "DELETE_PARTICIPANT_VIEW";
export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const ADD_LIST_PARTICIPANT = "ADD_LIST_PARTICIPANT";
export const DELETE_PARTICIPANT = "DELETE_PARTICIPANT";
export const CLEAR_PARTICIPANTS = "CLEAR_PARTICIPANTS";
export const FILTER_USER_BANCO = "FILTER_USER_BANCO";
export const NUMBER_CONTACTS = 300;
