export const DELETE_PARTICIPANT_VIEW = "DELETE_PARTICIPANT_VIEW";
export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const DELETE_PARTICIPANT = "DELETE_PARTICIPANT";
export const CLEAR_PARTICIPANTS = "CLEAR_PARTICIPANTS";
