export const LAST_VISIT_REVIEW = "ULTIMA_REVISION_FORMATO_DE_VISITA";
export const LAST_PIPELINE_REVIEW = "ULTIMA_REVISION_DE_PIPELINE";
export const LAST_PREVISIT_REVIEW = "ULTIMA_REVISION_DE_PREVISITA";
export const LAST_BUSINESS_REVIEW = "ULTIMA_REVISION_DE_PLANES_DE_NEGOCIO";
export const CONTENEDOR_VISOR_URL = "CONTENEDOR_VISOR_URL";
export const MESSAGE_SECURITY_FORM= "MENSAJE_SEGURIDAD_FORMULARIOS";