export const LINE_OF_BUSINESS = "LINE_OF_BUSINESS";
export const DISTRIBUTION_CHANNEL = "DISTRIBUTION_CHANNEL";
export const MAIN_CLIENTS = "MAIN_CLIENTS";
export const MAIN_SUPPLIER = "MAIN_SUPPLIER";
export const MAIN_COMPETITOR = "MAIN_COMPETITOR";
export const INT_OPERATIONS = "INT_OPERATIONS";
export const ORIGIN_EDIT_CLIENT = 'ORIGIN_EDIT_CLIENT';
export const ORIGIN_STUDY_CREDIT = 'ORIGIN_STUDY_CREDIT';

